/*
 CSQL-1: Added a CTE `source_deduplicated` to pre-process the source data.
 CSQL-2: Centralized all CAST operations into the CTE for clarity and to avoid repetition.
 CSQL-3: Added `QUALIFY ROW_NUMBER() OVER(...) = 1` to ensure the source provides exactly one row per join key, making the MERGE robust against duplicates and preventing runtime errors.
 CSQL-4: Removed the redundant `caldate = source.caldate` update, as `caldate` is part of the join key and cannot change.
*/
MERGE INTO `lmrs_ods.godailyhrs_seg1_pp_sum` AS target
USING (
  SELECT
    fac,
    dept,
    period,
    caldate,
    homedept,
    wrklddept,
    wrkldsub1,
    wrklddesc,
    daysopen,
    openyear,
    CAST(nonp AS NUMERIC) AS nonp,
    CAST(budvol AS NUMERIC) AS budvol,
    CAST(budprodhrs AS NUMERIC) AS budprodhrs,
    CAST(budnprodhrs AS NUMERIC) AS budnprodhrs,
    CAST(budproddls AS NUMERIC) AS budproddls,
    CAST(budnproddls AS NUMERIC) AS budnproddls,
    CAST(budptofctr AS NUMERIC) AS budptofctr,
    payperiod,
    rptmonth,
    CAST(targminvol AS NUMERIC) AS targminvol,
    CAST(targfixhrs AS NUMERIC) AS targfixhrs,
    CAST(targhruos AS NUMERIC) AS targhruos,
    CAST(pdrwrkldvol AS NUMERIC) AS pdrwrkldvol,
    CAST(prodacthrs AS NUMERIC) AS prodacthrs,
    CAST(regacthrs AS NUMERIC) AS regacthrs,
    CAST(nonpacthrs AS NUMERIC) AS nonpacthrs,
    CAST(otacthrs AS NUMERIC) AS otacthrs,
    CAST(clacthrs AS NUMERIC) AS clacthrs,
    CAST(cbackacthrs AS NUMERIC) AS cbackacthrs,
    CAST(pdptohrs AS NUMERIC) AS pdptohrs,
    CAST(pdinshrs AS NUMERIC) AS pdinshrs,
    CAST(pdnonphrs AS NUMERIC) AS pdnonphrs,
    CAST(prodactdls AS NUMERIC) AS prodactdls,
    CAST(regactdls AS NUMERIC) AS regactdls,
    CAST(otactdls AS NUMERIC) AS otactdls,
    CAST(clactdls AS NUMERIC) AS clactdls,
    CAST(cbackactdls AS NUMERIC) AS cbackactdls,
    CAST(pdptodls AS NUMERIC) AS pdptodls,
    CAST(pdinsdls AS NUMERIC) AS pdinsdls,
    CAST(pdnonpdls AS NUMERIC) AS pdnonpdls,
    CAST(tmpdata AS NUMERIC) AS tmpdata,
    xclosed,
    CAST(daybudvol AS NUMERIC) AS daybudvol,
    CAST(daybudprodhrs AS NUMERIC) AS daybudprodhrs,
    CAST(daybudnprodhrs AS NUMERIC) AS daybudnprodhrs,
    CAST(daybudearnrate AS NUMERIC) AS daybudearnrate,
    CAST(daybudptofctr AS NUMERIC) AS daybudptofctr,
    CAST(mthbudvol AS NUMERIC) AS mthbudvol,
    CAST(newearntot AS NUMERIC) AS newearntot,
    CAST(newearntotpaid AS NUMERIC) AS newearntotpaid,
    CAST(yearnhrs AS NUMERIC) AS yearnhrs,
    CAST(yearndls AS NUMERIC) AS yearndls,
    CAST(yearnhrspaid AS NUMERIC) AS yearnhrspaid,
    CAST(yearndlspaid AS NUMERIC) AS yearndlspaid,
    CAST(dayactvol AS NUMERIC) AS dayactvol,
    CAST(dayactprodhrs AS NUMERIC) AS dayactprodhrs,
    CAST(dayactnprodhrs AS NUMERIC) AS dayactnprodhrs,
    CAST(dayactproddls AS NUMERIC) AS dayactproddls,
    CAST(daybudproddls AS NUMERIC) AS daybudproddls,
    CAST(dayactnproddls AS NUMERIC) AS dayactnproddls,
    CAST(daybudnproddls AS NUMERIC) AS daybudnproddls,
    CAST(neworienhrs AS NUMERIC) AS neworienhrs,
    CAST(newinservhrs AS NUMERIC) AS newinservhrs,
    CAST(neworiendls AS NUMERIC) AS neworiendls,
    CAST(newinservdls AS NUMERIC) AS newinservdls,
    CAST(prodacthrstra AS NUMERIC) AS prodacthrstra,
    CAST(prodactdlstra AS NUMERIC) AS prodactdlstra,
    CAST(regactdlstra AS NUMERIC) AS regactdlstra,
    CAST(regacthrstra AS NUMERIC) AS regacthrstra,
    CAST(otacthrstra AS NUMERIC) AS otacthrstra,
    CAST(otactdlstra AS NUMERIC) AS otactdlstra,
    CAST(pdptothrstra AS NUMERIC) AS pdptothrstra,
    CAST(pdptodlstra AS NUMERIC) AS pdptodlstra,
    CAST(prodactdlsoffset AS NUMERIC) AS prodactdlsoffset,
    CAST(regactdlstraoffset AS NUMERIC) AS regactdlstraoffset,
    CAST(otactdlstraoffset AS NUMERIC) AS otactdlstraoffset,
    CAST(pdptodlstraoffset AS NUMERIC) AS pdptodlstraoffset
  FROM
    `lmrs_ods.hold1b1`
  QUALIFY
    ROW_NUMBER() OVER(PARTITION BY fac, dept, period, caldate) = 1
) AS source ON target.fac = source.fac
AND target.dept = source.dept
AND target.period = source.period
AND target.caldate = source.caldate
WHEN MATCHED THEN
UPDATE
SET
  homedept = source.homedept,
  wrklddept = source.wrklddept,
  wrkldsub1 = source.wrkldsub1,
  wrklddesc = source.wrklddesc,
  daysopen = source.daysopen,
  openyear = source.openyear,
  nonp = source.nonp,
  budvol = source.budvol,
  budprodhrs = source.budprodhrs,
  budnprodhrs = source.budnprodhrs,
  budproddls = source.budproddls,
  budnproddls = source.budnproddls,
  budptofctr = source.budptofctr,
  payperiod = source.payperiod,
  rptmonth = source.rptmonth,
  targminvol = source.targminvol,
  targfixhrs = source.targfixhrs,
  targhruos = source.targhruos,
  pdrwrkldvol = source.pdrwrkldvol,
  prodacthrs = source.prodacthrs,
  regacthrs = source.regacthrs,
  nonpacthrs = source.nonpacthrs,
  otacthrs = source.otacthrs,
  clacthrs = source.clacthrs,
  cbackacthrs = source.cbackacthrs,
  pdptohrs = source.pdptohrs,
  pdinshrs = source.pdinshrs,
  pdnonphrs = source.pdnonphrs,
  prodactdls = source.prodactdls,
  regactdls = source.regactdls,
  otactdls = source.otactdls,
  clactdls = source.clactdls,
  cbackactdls = source.cbackactdls,
  pdptodls = source.pdptodls,
  pdinsdls = source.pdinsdls,
  pdnonpdls = source.pdnonpdls,
  tmpdata = source.tmpdata,
  xclosed = source.xclosed,
  daybudvol = source.daybudvol,
  daybudprodhrs = source.daybudprodhrs,
  daybudnprodhrs = source.daybudnprodhrs,
  daybudearnrate = source.daybudearnrate,
  daybudptofctr = source.daybudptofctr,
  mthbudvol = source.mthbudvol,
  newearntot = source.newearntot,
  newearntotpaid = source.newearntotpaid,
  yearnhrs = source.yearnhrs,
  yearndls = source.yearndls,
  yearnhrspaid = source.yearnhrspaid,
  yearndlspaid = source.yearndlspaid,
  dayactvol = source.dayactvol,
  dayactprodhrs = source.dayactprodhrs,
  dayactnprodhrs = source.dayactnprodhrs,
  dayactproddls = source.dayactproddls,
  daybudproddls = source.daybudproddls,
  dayactnproddls = source.dayactnproddls,
  daybudnproddls = source.daybudnproddls,
  neworienhrs = source.neworienhrs,
  newinservhrs = source.newinservhrs,
  neworiendls = source.neworiendls,
  newinservdls = source.newinservdls,
  prodacthrstra = source.prodacthrstra,
  prodactdlstra = source.prodactdlstra,
  regactdlstra = source.regactdlstra,
  regacthrstra = source.regacthrstra,
  otacthrstra = source.otacthrstra,
  otactdlstra = source.otactdlstra,
  pdptothrstra = source.pdptothrstra,
  pdptodlstra = source.pdptodlstra,
  prodactdlsoffset = source.prodactdlsoffset,
  regactdlstraoffset = source.regactdlstraoffset,
  otactdlstraoffset = source.otactdlstraoffset,
  pdptodlstraoffset = source.pdptodlstraoffset
WHEN NOT MATCHED THEN
INSERT
  (fac, dept, period, caldate, homedept, wrklddept, wrkldsub1, wrklddesc, daysopen, openyear, nonp, budvol, budprodhrs, budnprodhrs, budproddls, budnproddls, budptofctr, payperiod, rptmonth, targminvol, targfixhrs, targhruos, pdrwrkldvol, prodacthrs, regacthrs, nonpacthrs, otacthrs, clacthrs, cbackacthrs, pdptohrs, pdinshrs, pdnonphrs, prodactdls, regactdls, otactdls, clactdls, cbackactdls, pdptodls, pdinsdls, pdnonpdls, tmpdata, xclosed, daybudvol, daybudprodhrs, daybudnprodhrs, daybudearnrate, daybudptofctr, mthbudvol, newearntot, newearntotpaid, yearnhrs, yearndls, yearnhrspaid, yearndlspaid, dayactvol, dayactprodhrs, dayactnprodhrs, dayactproddls, daybudproddls, dayactnproddls, daybudnproddls, neworienhrs, newinservhrs, neworiendls, newinservdls, prodacthrstra, prodactdlstra, regactdlstra, regacthrstra, otacthrstra, otactdlstra, pdptothrstra, pdptodlstra, prodactdlsoffset, regactdlstraoffset, otactdlstraoffset, pdptodlstraoffset)
VALUES
  (fac, dept, period, caldate, homedept, wrklddept, wrkldsub1, wrklddesc, daysopen, openyear, nonp, budvol, budprodhrs, budnprodhrs, budproddls, budnproddls, budptofctr, payperiod, rptmonth, targminvol, targfixhrs, targhruos, pdrwrkldvol, prodacthrs, regacthrs, nonpacthrs, otacthrs, clacthrs, cbackacthrs, pdptohrs, pdinshrs, pdnonphrs, prodactdls, regactdls, otactdls, clactdls, cbackactdls, pdptodls, pdinsdls, pdnonpdls, tmpdata, xclosed, daybudvol, daybudprodhrs, daybudnprodhrs, daybudearnrate, daybudptofctr, mthbudvol, newearntot, newearntotpaid, yearnhrs, yearndls, yearnhrspaid, yearndlspaid, dayactvol, dayactprodhrs, dayactnprodhrs, dayactproddls, daybudproddls, dayactnproddls, daybudnproddls, neworienhrs, newinservhrs, neworiendls, newinservdls, prodacthrstra, prodactdlstra, regactdlstra, regacthrstra, otacthrstra, otactdlstra, pdptothrstra, pdptodlstra, prodactdlsoffset, regactdlstraoffset, otactdlstraoffset, pdptodlstraoffset)
