CREATE OR REPLACE PROCEDURE `thcdnadevdata.idm.sp_fact_modified_anr_load_optimized`(IN inparam_facility_cd STRING, OUT OUT_PARAM INT64)
BEGIN

  /* --------------------------------------------------------------------------------------------------------------- */
  -- Proc name  : sp_fact_modified_anr_load
  -- Proc Desc  : Calculates MODIFIED_ANR using Plan, SRG, and Patient Class, and loads minimal data to a target table.
  /* --------------------------------------------------------------------------------------------------------------- */
  DECLARE V_FACILITY_CD STRING DEFAULT inparam_facility_cd;
  DECLARE V_SQL STRING;

  -- 1. Create and Load the Base Data Temp Table (Requires all three granularity columns)
  -- START OPTIMIZED QUERY
DECLARE V_START_DATE DATE DEFAULT DATE_ADD(DATE_TRUNC(DATE_ADD(CURRENT_DATE('America/Chicago'), INTERVAL -36 MONTH), QUARTER), INTERVAL -15 MONTH);

CREATE TEMP TABLE temp_fact_encounter_anr_hist_base_data
CLUSTER BY DISCHARGE_DT AS
WITH
  Encounters_Base AS (
    SELECT
      FE.DIM_FACILITY_SK,
      FE.DIM_HEALTH_PLAN_SK,
      FE.DIM_STD_REV_GRP_SK,
      FE.DIM_ENCOUNTER_TYPE_SK,
      FE.PATIENT_ACCOUNT_NBR,
      FE.DISCHARGE_DT,
      FE.TOTAL_CHARGES,
      FE.ADJUSTED_NET_REV,
      FE.PA_TOTAL_PAYMENTS,
      FE.FACILITY_CD
    FROM
      `thcdnadevdata.idm.fact_encounter` AS FE
    WHERE
      -- This predicate is the main performance bottleneck.
      LOWER(TRIM(FE.FACILITY_CD)) = LOWER(TRIM(V_FACILITY_CD))
      AND FE.DISCHARGE_DT >= V_START_DATE
  ),
  Encounters_Filtered AS (
    SELECT
      base.*
    FROM
      Encounters_Base AS base
    INNER JOIN
      `thcdnadevdata.idm.dim_encounter_type` AS DET
      ON base.DIM_ENCOUNTER_TYPE_SK = DET.DIM_ENCOUNTER_TYPE_SK
    WHERE
      -- This predicate effectively converted the original LEFT JOIN to an INNER JOIN.
      -- Applying it early reduces the row count for all downstream operations.
      DET.PATIENT_CLASS_CD IN ('I', 'O')
  )
SELECT
  DF.MRKT_ID,
  FE.FACILITY_CD,
  FE.PATIENT_ACCOUNT_NBR,
  FE.DISCHARGE_DT,
  DET.PATIENT_CLASS_CD,
  DHP.PLAN_ID,
  DSRG.SRG9_CD,
  FE.TOTAL_CHARGES,
  FE.ADJUSTED_NET_REV,
  FE.PA_TOTAL_PAYMENTS,
  CASE
    WHEN (DF.MRKT_ID IN ('M21', 'M13')) THEN 'ANR'
    WHEN (DF.MRKT_ID IN ('M16') OR DF.FACILITY_CD IN ('HMD', 'EMC')) THEN 'PAYMENTS'
  END AS CALC_FIELD
FROM
  Encounters_Filtered AS FE
  INNER JOIN `thcdnadevdata.idm.dim_facility` AS DF ON FE.DIM_FACILITY_SK = DF.DIM_FACILITY_SK
  LEFT JOIN `thcdnadevdata.idm.dim_health_plan` AS DHP ON FE.DIM_HEALTH_PLAN_SK = DHP.DIM_HEALTH_PLAN_SK AND DHP.DIM_HEALTH_PLAN_SK <> '-99'
  LEFT JOIN `thcdnadevdata.idm.dim_std_rev_grp` AS DSRG ON FE.DIM_STD_REV_GRP_SK = DSRG.DIM_STD_REV_GRP_SK AND DSRG.DIM_STD_REV_GRP_SK <> '-99'
  LEFT JOIN `thcdnadevdata.idm.dim_encounter_type` AS DET ON FE.DIM_ENCOUNTER_TYPE_SK = DET.DIM_ENCOUNTER_TYPE_SK AND DET.DIM_ENCOUNTER_TYPE_SK <> '-99'
WHERE
  (
    (DF.MRKT_ID IN ('M21', 'M13') AND COALESCE(FE.TOTAL_CHARGES, 0) <> COALESCE(FE.ADJUSTED_NET_REV, 0))
    OR (DF.MRKT_ID IN ('M16') AND COALESCE(FE.PA_TOTAL_PAYMENTS, 0) <> 0)
    OR (DF.FACILITY_CD IN ('HMD', 'EMC') AND COALESCE(FE.PA_TOTAL_PAYMENTS, 0) <> 0)
  );
-- END OPTIMIZED QUERY;

  -- 2. Create and Load the Summary Temp Table (Historical Rates: Plan and SRG)
  --    This logic uses all three columns for grouping as per the requirement.
  CREATE TEMPORARY TABLE temp_fact_encounter_anr_hist_summary CLUSTER BY FROM_DISCHARGE_DT, TO_DISCHARGE_DT AS
  WITH ANR_PLAN_HIST AS
  (
    SELECT
      DT.FROM_DISCHARGE_DT, DT.TO_DISCHARGE_DT, FACILITY_CD, PATIENT_CLASS_CD, PLAN_ID,
      CAST('PLAN' AS STRING) AS MEASURE_GROUP, CALC_FIELD AS MEASURE_NM,
      CAST(AVG(TOTAL_CHARGES) AS NUMERIC) AS AVG_TOTAL_CHARGES,
      CAST(AVG(CASE WHEN CALC_FIELD = 'ANR' THEN CAST(ADJUSTED_NET_REV AS FLOAT64) WHEN CALC_FIELD = 'PAYMENTS' THEN CAST(PA_TOTAL_PAYMENTS AS FLOAT64) ELSE NULL END) AS NUMERIC) AS MEASURE_VALUE,
      CAST(CASE WHEN CAST(AVG(TOTAL_CHARGES) AS NUMERIC) <> 0 THEN CAST(AVG(CASE WHEN CALC_FIELD = 'ANR' THEN CAST(ADJUSTED_NET_REV AS FLOAT64) WHEN CALC_FIELD = 'PAYMENTS' THEN CAST(PA_TOTAL_PAYMENTS AS FLOAT64) ELSE NULL END) AS NUMERIC) * 100.00 / CAST(CAST(AVG(TOTAL_CHARGES) AS NUMERIC) AS FLOAT64) ELSE NULL END AS NUMERIC) AS MEASURE_PERCENT,
      CAST(COUNT(CASE WHEN CALC_FIELD = 'ANR' THEN ADJUSTED_NET_REV WHEN CALC_FIELD = 'PAYMENTS' THEN PA_TOTAL_PAYMENTS ELSE NULL END) AS INT64) AS RECORD_COUNT
    FROM temp_fact_encounter_anr_hist_base_data Q1
    CROSS JOIN (
      SELECT cast(DATE_ADD(DATE_ADD(DATE_TRUNC( CURRENT_DATE('America/Chicago'),QUARTER),INTERVAL -15  MONTH),interval - (IDX*3) MONTH) as datetime) AS FROM_DISCHARGE_DT,
      CAST(DATE_ADD(DATE_ADD(DATE_TRUNC( CURRENT_DATE('America/Chicago'),QUARTER),INTERVAL -3  MONTH),INTERVAL - (IDX*3)  MONTH)-1 as datetime) AS TO_DISCHARGE_DT
      FROM UNNEST(GENERATE_ARRAY(0, 1023)) AS IDX
      WHERE cast(DATE_ADD(DATE_ADD(DATE_TRUNC( CURRENT_DATE('America/Chicago'),QUARTER),INTERVAL -15  MONTH),INTERVAL - (IDX*3) MONTH) as datetime)
      >= DATE_ADD(DATE_TRUNC( DATE_ADD(CURRENT_DATE('America/Chicago'), INTERVAL - 36 MONTH),QUARTER ),INTERVAL  -15 MONTH)
    ) DT
    WHERE Q1.DISCHARGE_DT BETWEEN DT.FROM_DISCHARGE_DT AND DT.TO_DISCHARGE_DT
    GROUP BY 1, 2, 3, 4, 5, 6, 7
    HAVING RECORD_COUNT >= 3
  )
  , ANR_SRG_HIST AS
  (
    SELECT
      DT.FROM_DISCHARGE_DT, DT.TO_DISCHARGE_DT, FACILITY_CD, PATIENT_CLASS_CD, SRG9_CD,
      CAST('SRG' AS STRING) AS MEASURE_GROUP, CALC_FIELD AS MEASURE_NM,
      CAST(AVG(TOTAL_CHARGES) AS NUMERIC) AS AVG_TOTAL_CHARGES,
      CAST(AVG(CASE WHEN CALC_FIELD = 'ANR' THEN CAST(ADJUSTED_NET_REV AS FLOAT64) WHEN CALC_FIELD = 'PAYMENTS' THEN CAST(PA_TOTAL_PAYMENTS AS FLOAT64) ELSE NULL END) AS NUMERIC) AS MEASURE_VALUE,
      CAST(CASE WHEN CAST(AVG(TOTAL_CHARGES) AS NUMERIC) <> 0 THEN (CAST(AVG(CASE WHEN CALC_FIELD = 'ANR' THEN CAST(ADJUSTED_NET_REV AS FLOAT64) WHEN CALC_FIELD = 'PAYMENTS' THEN CAST(PA_TOTAL_PAYMENTS AS FLOAT64) ELSE NULL END) AS NUMERIC)) * 100.00 / CAST(CAST(AVG(TOTAL_CHARGES) AS NUMERIC) AS FLOAT64) ELSE NULL END AS NUMERIC) AS MEASURE_PERCENT,
      CAST(COUNT(CASE WHEN CALC_FIELD = 'ANR' THEN ADJUSTED_NET_REV WHEN CALC_FIELD = 'PAYMENTS' THEN PA_TOTAL_PAYMENTS ELSE NULL END) AS INT64) AS RECORD_COUNT
    FROM temp_fact_encounter_anr_hist_base_data Q1
    CROSS JOIN (
      SELECT cast(DATE_ADD(DATE_ADD(DATE_TRUNC( CURRENT_DATE('America/Chicago'),QUARTER),INTERVAL -15  MONTH),interval - (IDX*3) MONTH) as datetime) AS FROM_DISCHARGE_DT,
      CAST(DATE_ADD(DATE_ADD(DATE_TRUNC( CURRENT_DATE('America/Chicago'),QUARTER),INTERVAL -3  MONTH),INTERVAL - (IDX*3)  MONTH)-1 as datetime) AS TO_DISCHARGE_DT
      FROM UNNEST(GENERATE_ARRAY(0, 1023)) AS IDX
      WHERE cast(DATE_ADD(DATE_ADD(DATE_TRUNC( CURRENT_DATE('America/Chicago'),QUARTER),INTERVAL -15  MONTH),INTERVAL - (IDX*3) MONTH) as datetime)
      >= DATE_ADD(DATE_TRUNC( DATE_ADD(CURRENT_DATE('America/Chicago'), INTERVAL - 36 MONTH),QUARTER ),INTERVAL  -15 MONTH)
    ) DT
    WHERE Q1.DISCHARGE_DT BETWEEN DT.FROM_DISCHARGE_DT AND DT.TO_DISCHARGE_DT
    GROUP BY 1, 2, 3, 4, 5, 6, 7
    HAVING RECORD_COUNT >= 3
  )
  SELECT * FROM ANR_PLAN_HIST
  UNION ALL
  SELECT * FROM ANR_SRG_HIST;

  -- 3. Calculate MODIFIED_ANR and Insert into Target Table

  delete from idm.fact_encounter_modified_anr where LOWER(TRIM(FACILITY_CD)) = LOWER(TRIM(V_FACILITY_CD)) ;

  -- START OPTIMIZED QUERY
INSERT INTO idm.fact_encounter_modified_anr
(
  FACILITY_CD,
  PATIENT_ACCOUNT_NBR,
  MODIFIED_ANR
)
WITH
ENC_base AS (
  SELECT
    FE.PATIENT_ACCOUNT_NBR,
    FE.TOTAL_CHARGES,
    FE.FACILITY_CD,
    DET.PATIENT_CLASS_CD,
    DHP.PLAN_ID,
    DSRG.SRG9_CD,
    DATE_ADD(DATE_TRUNC(FE.DISCHARGE_DT, QUARTER), INTERVAL -15 MONTH) AS ANR_HIST_BEGIN_DT,
    DATE_ADD(DATE_TRUNC(FE.DISCHARGE_DT, QUARTER), INTERVAL -3 MONTH) - 1 AS ANR_HIST_END_DT,
    CASE
      WHEN DF.MRKT_ID IN ('M21', 'M13') THEN FE.ADJUSTED_NET_REV
      WHEN DF.MRKT_ID IN ('M16') AND DF.FACILITY_CD NOT IN ('BMC') THEN FE.PA_TOTAL_PAYMENTS
      WHEN DF.FACILITY_CD IN ('HMD', 'EMC') THEN FE.PA_TOTAL_PAYMENTS
    END AS DEFAULT_ANR
  FROM
    thcdnadevdata.idm.fact_encounter AS FE
  INNER JOIN thcdnadevdata.idm.dim_facility AS DF
    ON FE.DIM_FACILITY_SK = DF.DIM_FACILITY_SK
  LEFT JOIN thcdnadevdata.idm.dim_health_plan AS DHP
    ON FE.DIM_HEALTH_PLAN_SK = DHP.DIM_HEALTH_PLAN_SK AND DHP.DIM_HEALTH_PLAN_SK <> '-99'
  LEFT JOIN thcdnadevdata.idm.dim_std_rev_grp AS DSRG
    ON FE.DIM_STD_REV_GRP_SK = DSRG.DIM_STD_REV_GRP_SK AND DSRG.DIM_STD_REV_GRP_SK <> '-99'
  LEFT JOIN thcdnadevdata.idm.dim_encounter_type AS DET
    ON FE.DIM_ENCOUNTER_TYPE_SK = DET.DIM_ENCOUNTER_TYPE_SK AND DET.DIM_ENCOUNTER_TYPE_SK <> '-99'
  WHERE
    (
      (DF.MRKT_ID IN ('M21', 'M13') AND COALESCE(FE.TOTAL_CHARGES, 0) = COALESCE(FE.ADJUSTED_NET_REV, 0))
      OR (DF.MRKT_ID IN ('M16') AND DF.FACILITY_CD NOT IN ('BMC') AND COALESCE(FE.PA_TOTAL_PAYMENTS, 0) = 0)
      OR (DF.FACILITY_CD IN ('HMD', 'EMC') AND COALESCE(FE.PA_TOTAL_PAYMENTS, 0) = 0)
    )
    AND DET.PATIENT_CLASS_CD IN ('I', 'O')
    AND FE.TOTAL_CHARGES <> 0
    AND FE.DISCHARGE_DT >= DATE_ADD(CURRENT_DATE('America/Chicago'), INTERVAL -36 MONTH)
    AND (LOWER(TRIM(FE.FACILITY_CD)) = LOWER(TRIM(V_FACILITY_CD))) -- Using placeholder V_FACILITY_CD for equivalence. Consider using a query parameter @V_FACILITY_CD.
),
H1_data AS (
  SELECT FACILITY_CD, PATIENT_CLASS_CD, PLAN_ID, FROM_DISCHARGE_DT, TO_DISCHARGE_DT, MEASURE_PERCENT
  FROM temp_fact_encounter_anr_hist_summary
  WHERE MEASURE_GROUP = 'PLAN'
),
H2_data AS (
  SELECT FACILITY_CD, PATIENT_CLASS_CD, PLAN_ID, FROM_DISCHARGE_DT, TO_DISCHARGE_DT, MEASURE_PERCENT
  FROM temp_fact_encounter_anr_hist_summary
  WHERE MEASURE_GROUP = 'SRG'
),
Enc_with_percent AS (
  SELECT
    ENC.FACILITY_CD,
    ENC.PATIENT_ACCOUNT_NBR,
    ENC.TOTAL_CHARGES,
    ENC.DEFAULT_ANR,
    CASE
      WHEN ENC.SRG9_CD = '65' THEN 2.0
      WHEN COALESCE(H1.MEASURE_PERCENT, 0) <> 0 THEN H1.MEASURE_PERCENT
      WHEN COALESCE(H2.MEASURE_PERCENT, 0) <> 0 THEN H2.MEASURE_PERCENT
      ELSE NULL
    END AS derived_percent
  FROM ENC_base AS ENC
  LEFT JOIN H1_data AS H1
    ON ENC.FACILITY_CD = H1.FACILITY_CD
    AND ENC.PATIENT_CLASS_CD = H1.PATIENT_CLASS_CD
    AND ENC.PLAN_ID = H1.PLAN_ID
    AND ENC.ANR_HIST_BEGIN_DT = H1.FROM_DISCHARGE_DT
    AND ENC.ANR_HIST_END_DT = H1.TO_DISCHARGE_DT
  LEFT JOIN H2_data AS H2
    ON ENC.FACILITY_CD = H2.FACILITY_CD
    AND ENC.PATIENT_CLASS_CD = H2.PATIENT_CLASS_CD
    AND ENC.SRG9_CD = H2.PLAN_ID -- Note: SRG9_CD is joined to PLAN_ID in H2
    AND ENC.ANR_HIST_BEGIN_DT = H2.FROM_DISCHARGE_DT
    AND ENC.ANR_HIST_END_DT = H2.TO_DISCHARGE_DT
)
SELECT
  FACILITY_CD,
  PATIENT_ACCOUNT_NBR,
  CAST(ROUND(
    CASE
      WHEN derived_percent IS NOT NULL THEN (derived_percent * CAST(TOTAL_CHARGES AS FLOAT64)) / 100.0
      ELSE DEFAULT_ANR
    END
  , 2) AS NUMERIC) AS MODIFIED_ANR
FROM Enc_with_percent;
-- END OPTIMIZED QUERY;

-- START OF OPTIMIZED QUERY: script_job_b9baf202c7b6ccd9078d31c5085151e5_4

INSERT INTO `thcdnadevdata.idm.fact_encounter_modified_anr` (
    PATIENT_ACCOUNT_NBR,
    FACILITY_CD,
    MODIFIED_ANR
)
SELECT
    FE.PATIENT_ACCOUNT_NBR,
    FE.FACILITY_CD,
    FE.PA_TOTAL_PAYMENTS AS MODIFIED_ANR
FROM
    `idm.fact_encounter` AS FE
WHERE
    -- Condition 1: Apply the variable-based filter. Placing this first may help reduce rows early.
    LOWER(TRIM(FE.FACILITY_CD)) = LOWER(TRIM(V_FACILITY_CD))
    -- Condition 2: Ensure the encounter belongs to a valid facility using a NULL-safe semi-join.
    AND EXISTS (
        SELECT 1
        FROM `thcdnadevdata.idm.dim_facility` AS DF
        WHERE
            FE.DIM_FACILITY_SK = DF.DIM_FACILITY_SK
            AND (
                (DF.MRKT_ID IN ('M16') AND DF.FACILITY_CD NOT IN ('BMC'))
                OR DF.FACILITY_CD IN ('HMD', 'EMC')
            )
    )
    -- Condition 3: Ensure the record does not already exist in the target table using a NULL-safe anti-join.
    AND NOT EXISTS (
        SELECT 1
        FROM `thcdnadevdata.idm.fact_encounter_modified_anr` AS TGT
        WHERE
            TGT.PATIENT_ACCOUNT_NBR = FE.PATIENT_ACCOUNT_NBR
            AND TGT.FACILITY_CD = FE.FACILITY_CD
    );

-- END OF OPTIMIZED QUERY: script_job_b9baf202c7b6ccd9078d31c5085151e5_4

  SET OUT_PARAM = 1;

-- EXCEPTION
-- 	WHEN ERROR THEN
-- 	--	ROLLBACK TRANSACTION;
-- 		SET V_LOG_MESSAGE = 'FAILED - Procedure ' || V_PROC_NAME || ', Reason: TRANSACTION_ABORTED - ' || REPLACE(@@error.message,'\'','\'\'');
-- 		SELECT '%', V_LOG_MESSAGE;
--       SET V_LOG_MESSAGE = 'FAILED - Procedure ' || V_PROC_NAME || ', ' || REPLACE(@@error.message,'\'','\'\'');
-- 		SELECT '%', V_LOG_MESSAGE;

--       SET OUT_PARAM = 0;
--       SELECT OUT_PARAM;

-- 		--RETURN;
-- RAISE USING message = FORMAT("Hey, you. On Execution of %s at %s, it caused an error: %s.", @@error.statement_text, @@error.formatted_stack_trace, @@error.message);

END;