CREATE TEMP TABLE SRC_STAGING_VISIT AS (
		SELECT
		V.V7HOSP AS HOSP_CD, CAST(V.V7PAT AS STRING) AS PATNO, Trim(V.V7PATT) AS V7PATT, V.V7ADMD, V.V7DISD, REGEXP_REPLACE(TRIM(V.V7PATC), '[ ]+', ' ') AS PATIENT_CLASS_CD,
    REGEXP_REPLACE(TRIM(V.V7PATT), '[ ]+', ' ') AS patient_class_type, G.G1LNAM, G.G1FNAM,
		CASE WHEN G.G1CELLPH = '0' OR G.G1CELLPH = '' OR G.G1CELLPH IS NULL OR LENGTH(TRIM(G.G1CELLPH)) < 10 THEN G.G1GRPH ELSE G.G1CELLPH END AS GUARANTORCELLPHONE, G.G1GREM,
    V.V7HOSP_THC_SRC, V.V7LCHD, 'DAAC' AS SOURCE_SYSTEM,
		FROM thcdnaproddata.daac_ods.daac_visit_hist AS V
    LEFT JOIN thcdnaproddata.daac_ods.daac_guar_hist AS G ON V.V7HOSP = G.G1HOSP AND V.V7PAT = G.G1PATN
		WHERE PARSE_DATE('%Y%m%d', CAST(V7LCHD AS STRING)) >= V_LAST_EXTRACT_DT AND
    (LOWER(TRIM(v7hosp_thc_src)) = LOWER(TRIM(V_FACILITY_CD))
		OR (LOWER(TRIM(v7hosp)) = LOWER(TRIM(V_FACILITY_CD)) AND v7hosp_thc_src IS NULL)) --AND (V.V7ADMD <> 99999999 OR V.V7DISD <> 99999999)

		UNION ALL

		SELECT
			V.V7HOSP AS HOSP_CD, TRIM(V.V7PAT) AS PATNO, Trim(V.V7PATT) AS V7PATT, V.V7ADMD, V.V7DISD,REGEXP_REPLACE(TRIM(V.V7PATC), '[ ]+', ' ') AS PATIENT_CLASS_CD,
      REGEXP_REPLACE(TRIM(V.V7PATT), '[ ]+', ' ') AS patient_class_type, V.G1NAME AS G1LNAM, ' ' AS G1FNAM,
			V.G1GRPH AS GUARANTORCELLPHONE,V.G1GREM,
      V.V7HOSP_THC_SRC, V.V7LCHD, V.SOURCE_SYSTEM,
		FROM thcdnaproddata.staging.nm_visit AS V
		WHERE PARSE_DATE('%Y%m%d', CAST(V7LCHD AS STRING)) >= V_LAST_EXTRACT_DT AND
    (LOWER(TRIM(v7hosp_thc_src)) = LOWER(TRIM(V_FACILITY_CD))
		OR (LOWER(TRIM(v7hosp)) = LOWER(TRIM(V_FACILITY_CD)) AND v7hosp_thc_src IS NULL)) AND V.V7PAT IS NOT NULL AND ((V.V7ADMD >= 20130101 AND V.V7ADMD <> 99999999 )
    OR (V.V7DISD >= 20130101 AND V.V7DISD <> 99999999) OR (V.V7DISD IS NULL AND V.V7ADMD IS NULL))
	)
