INSERT INTO `lmrs_idm.daily_performance_detail`
	(
fac ,
  facdesc ,
  dept ,
  ddesc ,
  jfacdept ,
  period ,
  caldate ,
  curday ,
  realmin ,
  varvol ,
  bdgtvol ,
  totvol ,
  wrklddept ,
  wrkldsub1 ,
  wrklddesc ,
  targminvol ,
  targhruos ,
  targfixhrs ,
  varhrs ,
  fixact ,
  varact ,
  varvar ,
  xptofctr ,
  earntot ,
  earndls ,
  xreghrs ,
  xregdls ,
  xothrs ,
  xotdls ,
  xclhrs ,
  xcldls ,
  xcbackhrs ,
  xcbackdls ,
  prdhrs ,
  prddls ,
  totvar ,
  totvardls ,
  gopdptohrs ,
  gopdptodls ,
  gopdinshrs ,
  gopdinsdls ,
  gopdnonphrs ,
  gopdnonpdls ,
  gneworienhrs ,
  gneworiendls ,
  gnewinservhrs ,
  gnewinservdls ,
  xallprodhrs ,
  overtimehrs ,
  overtimedls ,
  conthrs ,
  contdls ,
  dtargminvol ,
  dtotvol ,
  drealmin ,
  dvarvol ,
  dvarhrs ,
  dearntot ,
  dprdhrs ,
  dfixact ,
  dvaract ,
  dvarvar ,
  dtotvar ,
  dovertimehrs ,
  dconthrs ,
  dnonphrs ,
  mtargminvol ,
  mtotvol ,
  mrealmin ,
  mvarvol ,
  mvarhrs ,
  mearntot ,
  mprdhrs ,
  mfixact ,
  mvaract ,
  mvarvar ,
  mtotvar ,
  movertimehrs ,
  mconthrs ,
  mnonphrs ,
  daybudprodhrs ,
  daybudnprodhrs ,
  daybudptofctr ,
  daybdgtvol ,
  mthbudvol ,
  newearntot ,
  newearntotpaid ,
  newearntotb ,
  yearnhrs ,
  xearndls ,
  yearnhrspaid ,
  xearndlspaid ,
  dayactprodhrs ,
  dayactnprodhrs ,
  dayactvol ,
  daybudproddls ,
  dayactproddls ,
  daybudnproddls ,
  dayactnproddls ,
  gprodacthrstra ,
  gprodactdlstra ,
  gregactdlstra ,
  gregacthrstra ,
  gotacthrstra ,
  gotactdlstra ,
  gpdptothrstra ,
  gpdptodlstra ,
  gprodactdlsoffset ,
  gregactdlstraoffset ,
  gotactdlstraoffset ,
  gpdptodlstraoffset ,
  nreg ,
  source_system_id ,
  load_ts,
  timeperiod_identifier 

  )

    SELECT
    TRIM(d.fac) AS fac,
    xfac.facdesc,
    TRIM(d.dept) AS dept,
    xd.ddesc,
    TRIM(jfacdept) AS jfacdept,
    TRIM(period) AS period,
    caldate,
    TRIM(curday) AS curday,
    realmin,
    varvol,
    bdgtvol,
    totvol,
    TRIM(d.wrklddept) AS wrklddept,
    TRIM(d.wrkldsub1) AS wrkldsub1,
    TRIM(d.wrklddesc) AS wrklddesc,
    targminvol,
    targhruos,
    targfixhrs,
    varhrs,
    fixact,
    varact,
    varvar,
    xptofctr,
    earntot,
    earndls,
    xreghrs,
    xregdls,
    xothrs,
    xotdls,
    xclhrs,
    xcldls,
    xcbackhrs,
    xcbackdls,
    prdhrs,
    prddls,
    totvar,
    totvardls,
    gopdptohrs,
    gopdptodls,
    gopdinshrs,
    gopdinsdls,
    gopdnonphrs,
    gopdnonpdls,
    gneworienhrs,
    gneworiendls,
    gnewinservhrs,
    gnewinservdls,
    xallprodhrs,
    overtimehrs,
    overtimedls,
    conthrs,
    contdls,
    dtargminvol,
    dtotvol,
    drealmin,
    dvarvol,
    dvarhrs,
    dearntot,
    dprdhrs,
    dfixact,
    dvaract,
    dvarvar,
    dtotvar,
    dovertimehrs,
    dconthrs,
    dnonphrs,
    mtargminvol,
    mtotvol,
    mrealmin,
    mvarvol,
    mvarhrs,
    mearntot,
    mprdhrs,
    mfixact,
    mvaract,
    mvarvar,
    mtotvar,
    movertimehrs,
    mconthrs,
    mnonphrs,
    daybudprodhrs,
    daybudnprodhrs,
    daybudptofctr,
    daybdgtvol,
    mthbudvol,
    newearntot,
    newearntotpaid,
    newearntotb,
    yearnhrs,
    xearndls,
    yearnhrspaid,
    xearndlspaid,
    dayactprodhrs,
    dayactnprodhrs,
    dayactvol,
    daybudproddls,
    dayactproddls,
    daybudnproddls,
    dayactnproddls,
    gprodacthrstra,
    gprodactdlstra,
    gregactdlstra,
    gregacthrstra,
    gotacthrstra,
    gotactdlstra,
    gpdptothrstra,
    gpdptodlstra,
    gprodactdlsoffset,
    gregactdlstraoffset,
    gotactdlstraoffset,
    gpdptodlstraoffset,
    TRIM(nreg) AS nreg,
    'lmrs' AS source_system_id,
    DATETIME(TIMESTAMP(CURRENT_DATETIME), "America/Chicago") AS load_ts
    , d.timeperiod_identifier
from
   ( select *, 'PP' as timeperiod_identifier from `lmrs_ods.divdaily_seg1_pp` 
    union all
    select *, 'MM' as timeperiod_identifier from `lmrs_ods.divdaily_seg1_mm`
    union all
    select *, 'SD' as timeperiod_identifier from `lmrs_ods.divdaily_seg1_sd`
  )
     d
LEFT JOIN `lmrs_staging.vw_xlbfac` xfac ON TRIM(d.fac) = xfac.fac
LEFT JOIN `lmrs_staging.vw_xgendept` xd ON CONCAT(TRIM(d.fac), TRIM(d.dept)) = xd.jdept
LEFT JOIN `lmrs_ods.sattlco` s ON TRIM(d.fac) = TRIM(s.tlco)
