merge into `lmrs_ods.godailyhrs_seg1_pp_sum` as target
using `lmrs_ods.hold1b1` as source
on target.fac = source.fac
   and target.dept = source.dept
   and target.period = source.period
  and target.caldate = source.caldate
 
when matched then
update set
  caldate = source.caldate,
  homedept = source.homedept,
  wrklddept = source.wrklddept,
  wrkldsub1 = source.wrkldsub1,
  wrklddesc = source.wrklddesc,
  daysopen = source.daysopen,
  openyear = source.openyear,
  nonp = cast(source.nonp as numeric),
  budvol = cast(source.budvol as numeric),
  budprodhrs = cast(source.budprodhrs as numeric),
  budnprodhrs = cast(source.budnprodhrs as numeric),
  budproddls = cast(source.budproddls as numeric),
  budnproddls = cast(source.budnproddls as numeric),
  budptofctr = cast(source.budptofctr as numeric),
  payperiod = source.payperiod,
  rptmonth = source.rptmonth,
  targminvol = cast(source.targminvol as numeric),
  targfixhrs = cast(source.targfixhrs as numeric),
  targhruos = cast(source.targhruos as numeric),
  pdrwrkldvol = cast(source.pdrwrkldvol as numeric),
  prodacthrs = cast(source.prodacthrs as numeric),
  regacthrs = cast(source.regacthrs as numeric),
  nonpacthrs = cast(source.nonpacthrs as numeric),
  otacthrs = cast(source.otacthrs as numeric),
  clacthrs = cast(source.clacthrs as numeric),
  cbackacthrs = cast(source.cbackacthrs as numeric),
  pdptohrs = cast(source.pdptohrs as numeric),
  pdinshrs = cast(source.pdinshrs as numeric),
  pdnonphrs = cast(source.pdnonphrs as numeric),
  prodactdls = cast(source.prodactdls as numeric),
  regactdls = cast(source.regactdls as numeric),
  otactdls = cast(source.otactdls as numeric),
  clactdls = cast(source.clactdls as numeric),
  cbackactdls = cast(source.cbackactdls as numeric),
  pdptodls = cast(source.pdptodls as numeric),
  pdinsdls = cast(source.pdinsdls as numeric),
  pdnonpdls = cast(source.pdnonpdls as numeric),
  tmpdata = cast(source.tmpdata as numeric),
  xclosed = source.xclosed,
  daybudvol = cast(source.daybudvol as numeric),
  daybudprodhrs = cast(source.daybudprodhrs as numeric),
  daybudnprodhrs = cast(source.daybudnprodhrs as numeric),
  daybudearnrate = cast(source.daybudearnrate as numeric),
  daybudptofctr = cast(source.daybudptofctr as numeric),
  mthbudvol = cast(source.mthbudvol as numeric),
  newearntot = cast(source.newearntot as numeric),
  newearntotpaid = cast(source.newearntotpaid as numeric),
  yearnhrs = cast(source.yearnhrs as numeric),
  yearndls = cast(source.yearndls as numeric),
  yearnhrspaid = cast(source.yearnhrspaid as numeric),
  yearndlspaid = cast(source.yearndlspaid as numeric),
  dayactvol = cast(source.dayactvol as numeric),
  dayactprodhrs = cast(source.dayactprodhrs as numeric),
  dayactnprodhrs = cast(source.dayactnprodhrs as numeric),
  dayactproddls = cast(source.dayactproddls as numeric),
  daybudproddls = cast(source.daybudproddls as numeric),
  dayactnproddls = cast(source.dayactnproddls as numeric),
  daybudnproddls = cast(source.daybudnproddls as numeric),
  neworienhrs = cast(source.neworienhrs as numeric),
  newinservhrs = cast(source.newinservhrs as numeric),
  neworiendls = cast(source.neworiendls as numeric),
  newinservdls = cast(source.newinservdls as numeric),
  prodacthrstra = cast(source.prodacthrstra as numeric),
  prodactdlstra = cast(source.prodactdlstra as numeric),
  regactdlstra = cast(source.regactdlstra as numeric),
  regacthrstra = cast(source.regacthrstra as numeric),
  otacthrstra = cast(source.otacthrstra as numeric),
  otactdlstra = cast(source.otactdlstra as numeric),
  pdptothrstra = cast(source.pdptothrstra as numeric),
  pdptodlstra = cast(source.pdptodlstra as numeric),
  prodactdlsoffset = cast(source.prodactdlsoffset as numeric),
  regactdlstraoffset = cast(source.regactdlstraoffset as numeric),
  otactdlstraoffset = cast(source.otactdlstraoffset as numeric),
  pdptodlstraoffset = cast(source.pdptodlstraoffset as numeric)
 
when not matched then
insert (
  fac, dept, period, caldate, homedept, wrklddept, wrkldsub1, wrklddesc, daysopen, openyear, nonp, budvol,
  budprodhrs, budnprodhrs, budproddls, budnproddls, budptofctr, payperiod, rptmonth,
  targminvol, targfixhrs, targhruos, pdrwrkldvol,
  prodacthrs, regacthrs, nonpacthrs, otacthrs, clacthrs, cbackacthrs,
  pdptohrs, pdinshrs, pdnonphrs,
  prodactdls, regactdls, otactdls, clactdls, cbackactdls, pdptodls, pdinsdls, pdnonpdls, tmpdata,
  xclosed, daybudvol, daybudprodhrs, daybudnprodhrs, daybudearnrate, daybudptofctr,
  mthbudvol, newearntot, newearntotpaid, yearnhrs, yearndls, yearnhrspaid, yearndlspaid,
  dayactvol, dayactprodhrs, dayactnprodhrs, dayactproddls, daybudproddls, dayactnproddls, daybudnproddls,
  neworienhrs, newinservhrs, neworiendls, newinservdls,
  prodacthrstra, prodactdlstra,
  regactdlstra, regacthrstra,
  otacthrstra, otactdlstra,
  pdptothrstra, pdptodlstra,
  prodactdlsoffset, regactdlstraoffset, otactdlstraoffset, pdptodlstraoffset
)
values (
  source.fac, source.dept, source.period, source.caldate, source.homedept, source.wrklddept, source.wrkldsub1, source.wrklddesc, source.daysopen, source.openyear, cast(source.nonp as numeric), cast(source.budvol as numeric),
  cast(source.budprodhrs as numeric), cast(source.budnprodhrs as numeric), cast(source.budproddls as numeric), cast(source.budnproddls as numeric), cast(source.budptofctr as numeric), source.payperiod, source.rptmonth,
  cast(source.targminvol as numeric), cast(source.targfixhrs as numeric), cast(source.targhruos as numeric), cast(source.pdrwrkldvol as numeric),
  cast(source.prodacthrs as numeric), cast(source.regacthrs as numeric), cast(source.nonpacthrs as numeric), cast(source.otacthrs as numeric), cast(source.clacthrs as numeric), cast(source.cbackacthrs as numeric),
  cast(source.pdptohrs as numeric), cast(source.pdinshrs as numeric), cast(source.pdnonphrs as numeric),
  cast(source.prodactdls as numeric), cast(source.regactdls as numeric), cast(source.otactdls as numeric), cast(source.clactdls as numeric), cast(source.cbackactdls as numeric), cast(source.pdptodls as numeric), cast(source.pdinsdls as numeric), cast(source.pdnonpdls as numeric), cast(source.tmpdata as numeric),
  source.xclosed, cast(source.daybudvol as numeric), cast(source.daybudprodhrs as numeric), cast(source.daybudnprodhrs as numeric), cast(source.daybudearnrate as numeric), cast(source.daybudptofctr as numeric),
  cast(source.mthbudvol as numeric), cast(source.newearntot as numeric), cast(source.newearntotpaid as numeric), cast(source.yearnhrs as numeric), cast(source.yearndls as numeric), cast(source.yearnhrspaid as numeric), cast(source.yearndlspaid as numeric),
  cast(source.dayactvol as numeric), cast(source.dayactprodhrs as numeric), cast(source.dayactnprodhrs as numeric), cast(source.dayactproddls as numeric), cast(source.daybudproddls as numeric), cast(source.dayactnproddls as numeric), cast(source.daybudnproddls as numeric),
  cast(source.neworienhrs as numeric), cast(source.newinservhrs as numeric), cast(source.neworiendls as numeric), cast(source.newinservdls as numeric),
  cast(source.prodacthrstra as numeric), cast(source.prodactdlstra as numeric),
  cast(source.regactdlstra as numeric), cast(source.regacthrstra as numeric),
  cast(source.otacthrstra as numeric), cast(source.otactdlstra as numeric),
  cast(source.pdptothrstra as numeric), cast(source.pdptodlstra as numeric),
  cast(source.prodactdlsoffset as numeric), cast(source.regactdlstraoffset as numeric), cast(source.otactdlstraoffset as numeric), cast(source.pdptodlstraoffset as numeric)
)
